# Generated by Django 5.2.4 on 2026-03-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
